# Generated by Django 3.2.5 on 2021-07-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210706_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved'), ('x', 'Missing')], default='m', help_text='Book                                   availability', max_length=1),
        ),
    ]
