# Generated by Django 3.2.5 on 2021-07-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210707_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentPrepTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('h', 'On Hold'), ('c', 'Complete'), ('p', 'In Progress'), ('f', 'Failed')], default='m', help_text='Book                                   availability', max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Component_Prep',
            new_name='Component_Prep_Tasks',
        ),
        migrations.DeleteModel(
            name='Component_Prep_Task_Instance',
        ),
    ]
