# Generated by Django 3.2.5 on 2021-07-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210707_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentpreptaskinstance',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='component_preptask',
            name='description',
            field=models.TextField(help_text='Task                                   description to aid new employees', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='componentpreptaskinstance',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.component_preptask'),
        ),
        migrations.AlterField(
            model_name='component_preptask',
            name='title',
            field=models.CharField(help_text=' Name of a                             component prep task', max_length=100),
        ),
    ]
