# Generated by Django 3.2.5 on 2021-07-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210707_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='CPtasks',
            field=models.ManyToManyField(help_text='Select                                      the nessessacy component prep tasks                                          to be completed.', to='catalog.Component_PrepTask'),
        ),
    ]
