# Generated by Django 3.2.5 on 2021-07-07 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_componentpreptaskinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpreptaskinstance',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.part'),
        ),
    ]
