# Generated by Django 3.2.5 on 2021-07-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_componentpreptaskinstance_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpreptaskinstance',
            name='part',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
