# Generated by Django 3.2.5 on 2021-07-08 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210708_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 8, 26, 21, 894342), verbose_name='time published'),
        ),
    ]
