# Generated by Django 3.2.5 on 2021-07-07 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_part_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 22, 27, 14, 273401, tzinfo=utc), verbose_name='time published'),
        ),
    ]
