# Generated by Django 3.2.5 on 2021-07-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_componentpreptaskinstance_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_preptask',
            name='description',
            field=models.TextField(blank=True, help_text='Task                                   description to aid new employees', max_length=1000, null=True),
        ),
    ]
