# Generated by Django 3.2.5 on 2021-07-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_component_preptask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpreptaskinstance',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.part'),
        ),
    ]
