# Generated by Django 3.2.5 on 2021-07-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_part_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpreptaskinstance',
            name='status',
            field=models.CharField(choices=[('a', 'Not Started'), ('h', 'On Hold'), ('c', 'Complete'), ('p', 'In Progress'), ('f', 'Failed')], default='a', help_text='Set                                   task completion status', max_length=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='CPtasks',
            field=models.ManyToManyField(help_text='Select                                      the component prep tasks                                          to be completed.', to='catalog.Component_PrepTask'),
        ),
    ]
