# Generated by Django 3.2.5 on 2021-07-11 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20210712_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=' Name of a                             component prep task', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Task                                   description to aid new employees', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackingTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('a', 'Not Started'), ('h', 'On Hold'), ('c', 'Complete'), ('p', 'In Progress'), ('f', 'Failed')], default='a', help_text='Set                                   task completion status', max_length=1)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.part')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
