# Generated by Django 3.2.5 on 2021-07-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_stackingtask_stackingtaskinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='Stacktasks',
            field=models.ManyToManyField(help_text='Select                                         the required stacking tasks.', to='catalog.StackingTask'),
        ),
    ]
