# Generated by Django 3.2.5 on 2021-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_part_stacktasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component_PrepTask',
            new_name='Component_Prep_Task',
        ),
        migrations.RenameModel(
            old_name='StackingTask',
            new_name='Stacking_Task',
        ),
        migrations.RemoveField(
            model_name='part',
            name='CPtasks',
        ),
        migrations.RemoveField(
            model_name='part',
            name='Stacktasks',
        ),
        migrations.AddField(
            model_name='part',
            name='Component_Prep_tasks',
            field=models.ManyToManyField(help_text='Select                                      the component prep tasks                                          to be completed.', to='catalog.Component_Prep_Task'),
        ),
        migrations.AddField(
            model_name='part',
            name='Stacking_tasks',
            field=models.ManyToManyField(help_text='Select                                         the required stacking tasks.', to='catalog.Stacking_Task'),
        ),
    ]
