# Generated by Django 3.2.5 on 2021-07-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_sheet_metal_forming_task_sheet_metal_forming_task_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet_metal_forming_task_instance',
            options={'ordering': ['status']},
        ),
    ]
