# Generated by Django 3.2.5 on 2021-07-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_alter_sheet_metal_forming_task_instance_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sheet_Metal_Forming_Task',
            new_name='Forming_Task',
        ),
        migrations.RenameModel(
            old_name='Sheet_Metal_Forming_Task_Instance',
            new_name='Forming_Task_Instance',
        ),
    ]
