# Generated by Django 3.2.5 on 2021-07-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20210713_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forming_Task_Instance',
            new_name='FormingTaskInstance',
        ),
    ]
