# Generated by Django 3.2.5 on 2021-07-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_rename_forming_task_instance_formingtaskinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='Forming_tasks',
            field=models.ManyToManyField(help_text='Select                                           the required forming tasks.', to='catalog.Forming_Task'),
        ),
    ]
