# Generated by Django 3.2.5 on 2021-07-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_part_forming_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Plate_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the Name                     of a header plate machining task', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPlateTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
