# Generated by Django 3.2.5 on 2021-07-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_header_plate_task_headerplatetaskinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerplatetaskinstance',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='headerplatetaskinstance',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.part'),
        ),
        migrations.AddField(
            model_name='headerplatetaskinstance',
            name='status',
            field=models.CharField(choices=[('a', 'Not Started'), ('h', 'On Hold'), ('c', 'Complete'), ('p', 'In Progress'), ('f', 'Failed')], default='a', help_text='Set                                   task completion status', max_length=1),
        ),
    ]
