# Generated by Django 3.2.5 on 2021-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20210713_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='Header_Plate_tasks',
            field=models.ManyToManyField(help_text='                                                Select The nessessary header                                                     plate tasks', to='catalog.Header_Plate_Task'),
        ),
    ]
