# Generated by Django 3.2.5 on 2021-07-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_wire_cut_task_wirecuttaskinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='Wire_Cut_tasks',
            field=models.ManyToManyField(help_text='                                            Select the nessessary wire cut                                                tasks', to='catalog.Wire_Cut_Task'),
        ),
        migrations.AlterField(
            model_name='part',
            name='Pitching_tasks',
            field=models.ManyToManyField(help_text='                                            Select the nessessary pitching                                                 tasks', to='catalog.Pitching_Task'),
        ),
    ]
