# Generated by Django 3.2.5 on 2021-07-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20210714_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
