# Generated by Django 3.2.5 on 2021-07-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_part_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['serial']},
        ),
    ]
