# Generated by Django 3.2.5 on 2021-07-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_alter_part_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['title', 'serial']},
        ),
    ]
