# Generated by Django 3.2.5 on 2021-07-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_alter_part_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='time published'),
        ),
    ]
