# Generated by Django 3.2.5 on 2021-07-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_alter_part_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_prep_task',
            name='finishtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='component_prep_task',
            name='starttime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='component_prep_task',
            name='totaltime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
