# Generated by Django 3.2.5 on 2021-07-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_auto_20210721_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_prep_task',
            name='finishtime',
        ),
        migrations.RemoveField(
            model_name='component_prep_task',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='component_prep_task',
            name='totaltime',
        ),
        migrations.AddField(
            model_name='componentpreptaskinstance',
            name='finishtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='componentpreptaskinstance',
            name='starttime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='componentpreptaskinstance',
            name='totaltime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
