# Generated by Django 3.2.5 on 2021-07-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_auto_20210721_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpreptaskinstance',
            name='timetostart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='componentpreptaskinstance',
            name='timetostartnum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
