# Generated by Django 3.2.5 on 2021-07-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_auto_20210722_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='archive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
