# Generated by Django 3.2.5 on 2021-07-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_componentpreptaskinstance_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentpreptaskinstance',
            name='serial',
        ),
    ]
