# Generated by Django 3.2.5 on 2021-09-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_remove_componentpreptaskinstance_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component_prep_task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='component_prep_task',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
