# Generated by Django 3.2.5 on 2021-10-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_auto_20211028_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='priority',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
