# Generated by Django 3.2.5 on 2021-10-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_alter_part_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentpreptaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='deburrtaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='formingtaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='headerplatetaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='pitchingtaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='platingtaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='stackingtaskinstance',
            options={'ordering': ['status', 'part']},
        ),
        migrations.AlterModelOptions(
            name='wirecuttaskinstance',
            options={'ordering': ['status', 'part']},
        ),
    ]
