# Generated by Django 3.2.5 on 2021-10-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_auto_20211028_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stacking_task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stacking_task',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
