# Generated by Django 3.2.5 on 2021-10-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_auto_20211028_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpreptaskinstance',
            name='status',
            field=models.IntegerField(choices=[('2', 'Not Started'), ('3', 'On Hold'), ('10', 'Complete'), ('1', 'In Progress')], default='a', help_text='Set                                   task completion status'),
        ),
    ]
