# Generated by Django 3.2.5 on 2021-10-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_alter_componentpreptaskinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpreptaskinstance',
            name='status',
            field=models.IntegerField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default=2, help_text='Set                                   task completion status'),
        ),
    ]
