# Generated by Django 3.2.5 on 2021-10-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_alter_formingtaskinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackingtaskinstance',
            name='status',
            field=models.CharField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default=2, help_text='Set                                   task completion status', max_length=1),
        ),
    ]
