# Generated by Django 3.2.5 on 2021-10-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0090_auto_20211101_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirecuttaskinstance',
            name='status',
            field=models.IntegerField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default=2, help_text='Set task completion status'),
        ),
    ]
