# Generated by Django 3.2.5 on 2021-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_alter_headerplatetaskinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deburrtaskinstance',
            name='createtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deburrtaskinstance',
            name='status',
            field=models.CharField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default='a', help_text='Set task completion status', max_length=1),
        ),
        migrations.AlterField(
            model_name='platingtaskinstance',
            name='status',
            field=models.IntegerField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default='a', help_text='Set task completion status'),
        ),
    ]
