# Generated by Django 3.2.5 on 2021-11-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_auto_20211102_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deburrtaskinstance',
            name='createtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deburrtaskinstance',
            name='status',
            field=models.IntegerField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default=2, help_text='Set task completion status'),
        ),
        migrations.AlterField(
            model_name='platingtaskinstance',
            name='status',
            field=models.IntegerField(choices=[(2, 'Not Started'), (3, 'On Hold'), (10, 'Complete'), (1, 'In Progress')], default=2, help_text='Set task completion status'),
        ),
    ]
