# Generated by Django 3.2.5 on 2021-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0095_auto_20211102_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='Work_Order',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
