# Generated by Django 3.2.5 on 2021-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0096_part_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='core_type',
            field=models.CharField(choices=[('Rad', 'Radiator'), ('Cac', 'Intercooler'), ('Oil', 'Oilcooler'), ('Ers', 'ERS cooler')], default='Rad', help_text='Set Core Type', max_length=40),
        ),
    ]
