# Generated by Django 3.2.5 on 2021-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0097_part_core_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='Work_Order',
            field=models.CharField(help_text='Define Work Order No', max_length=6, null=True),
        ),
    ]
