# Generated by Django 3.2.5 on 2021-11-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0098_alter_part_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='core_type',
            field=models.CharField(choices=[('Radiator', 'Radiator'), ('Intercooler', 'Intercooler'), ('Oilcooler', 'Oilcooler'), ('ERS cooler', 'ERS cooler')], default='Rad', help_text='Set Core Type', max_length=40),
        ),
    ]
